#!/bin/sh

# DEFINITION OF PATHS
cd ..
export CORSOCXX_UTIL=`pwd`
cd particleHist_v6
echo `pwd`
export ANALYSIS_PATH=`pwd`


#####################################################################

# CREATION OF LIBRARIES: one for each analyser
export LIB_NAME=AnalysisFramework
echo "compile ${LIB_NAME}"  # prints on terminal when here
cd "${ANALYSIS_PATH}/${LIB_NAME}"  # change local directory
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"  # remove previous library
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" *.cc  # compilation command

export LIB_NAME=AnalysisObjects
echo "compile ${LIB_NAME}"
cd "${ANALYSIS_PATH}/${LIB_NAME}"
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" *.cc

export LIB_NAME=AnalysisUtilities
echo "compile ${LIB_NAME}"
cd "${ANALYSIS_PATH}/${LIB_NAME}"
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" *.cc

#####################################################################

# CREATION OF LIBRARIES: one for each plugin
cd "${ANALYSIS_PATH}/AnalysisPlugins"

export LIB_NAME=EventDump
echo "compile ${LIB_NAME}"
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" "${LIB_NAME}.cc"

export LIB_NAME=ParticleMass
echo "compile ${LIB_NAME}"
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
`root-config --cflags` \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" "${LIB_NAME}.cc"

export LIB_NAME=ParticleLifetime
echo "compile ${LIB_NAME}"
rm -f "${ANALYSIS_PATH}/lib${LIB_NAME}.so"
g++ -Wall -fPIC -shared -I. -I "${CORSOCXX_UTIL}" -I "${ANALYSIS_PATH}" \
`root-config --cflags`                                              \
-o "${ANALYSIS_PATH}/lib${LIB_NAME}.so" "${LIB_NAME}.cc"

#####################################################################

# Creation of multiple executables with call to fake .cc file (everything is in the librearies)
cd "${ANALYSIS_PATH}"

export EXE_NAME=runDump
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
g++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}         \
-o ${EXE_NAME} dum.cc -L ${ANALYSIS_PATH} -Wl,--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lEventDump

export EXE_NAME=runMass
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
g++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}         \
-o ${EXE_NAME} dum.cc -L ${ANALYSIS_PATH} -Wl,--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lParticleMass `root-config --libs`

export EXE_NAME=runTime
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
g++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}         \
-o ${EXE_NAME} dum.cc -L ${ANALYSIS_PATH} -Wl,--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lParticleLifetime `root-config --libs`

export EXE_NAME=runAll
echo "compile " ${EXE_NAME}
rm -f ${EXE_NAME}
g++ -Wall -fPIC -I. -I ${ANALYSIS_PATH} -I ${CORSOCXX_UTIL}         \
-o ${EXE_NAME} dum.cc -L ${ANALYSIS_PATH} -Wl,--no-as-needed        \
-lAnalysisFramework -lAnalysisObjects -lAnalysisUtilities           \
-lEventDump -lParticleLifetime -lParticleMass `root-config --libs`

# Examples:

# DUMP INFORMATION
#./runDump input particle_events.txt dump
#./runDump sim 2000 dump

# PLOT MASS (Necessary specify the masses ranges)
#./runMass input particle_events.txt ranges massRanges plot massHist_input.root
#./runMass sim 3000 ranges massRanges plot massHist_sim.root

# PLOT TIME (Necessary specify the lifetime fit parameters)
#./runTime input particle_events.txt fit particleFitters time timeHist_input.root
#./runTime sim 3000 fit particleFitters time timeHist_sim.root

# PLOT ALL (Necessary specify the masses ranges and the lifetime fit parameters if the relative analysis mode input is present)
#./runAll input particle_events.txt ranges massRanges fit particleFitters plot hist_input.root time hist_input.root
#./runAll sim 3000 ranges massRanges fit particleFitters plot hist_sim.root time hist_sim.root
